# Generated by Django 3.1.1 on 2020-11-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=60)),
                ('application', models.CharField(max_length=60)),
                ('deploy_dir', models.CharField(max_length=100)),
                ('log_dir', models.CharField(max_length=100)),
                ('local_ip', models.CharField(max_length=18)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=15)),
                ('cname', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('idc_address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(max_length=20)),
                ('assistant', models.CharField(max_length=10)),
                ('assistant_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('local_ip', models.CharField(max_length=15)),
                ('public_ip', models.CharField(max_length=15)),
                ('ssh_port', models.CharField(max_length=6)),
                ('environment', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('t_image', models.CharField(default='http://www.qq.com', max_length=300)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devops.user')),
            ],
        ),
        migrations.CreateModel(
            name='DeployPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_version', models.IntegerField(max_length=3)),
                ('second_version', models.IntegerField(max_length=3)),
                ('third_version', models.IntegerField(max_length=3)),
                ('git_url', models.CharField(max_length=32)),
                ('git_version', models.CharField(max_length=32)),
                ('deploy_time', models.DateTimeField(max_length=8)),
                ('UAT_status', models.IntegerField(max_length=1)),
                ('PREIDC_status', models.IntegerField(max_length=1)),
                ('IDC_status', models.IntegerField(max_length=1)),
                ('exec_status', models.IntegerField(max_length=1)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Business_application', to='devops.business')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Business_business', to='devops.business')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Device_device', to='devops.device')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_leader', to='devops.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Business_project', to='devops.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='devops.user'),
        ),
    ]
