# Generated by Django 3.1.1 on 2020-09-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=60)),
                ('ip', models.CharField(max_length=15)),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('idc_address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(max_length=20)),
                ('assistant', models.CharField(max_length=10)),
                ('assistant_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('local_ip', models.CharField(max_length=15)),
                ('public_ip', models.CharField(max_length=15)),
                ('ssh_port', models.CharField(max_length=6)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('t_image', models.CharField(default='http://www.qq.com', max_length=300)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.user')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=60)),
                ('application', models.CharField(max_length=60)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devops.user')),
            ],
        ),
    ]
